apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: artifactoryproinstances.operator.k8s.trask.cz
spec:
  group: operator.k8s.trask.cz
  names:
    kind: ArtifactoryProInstance
    listKind: ArtifactoryProInstanceList
    singular: artifactoryproinstance
    plural: artifactoryproinstances
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
